apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - name: springboot
        image: jaisabhi1/spring-boot-mongo
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    name: springboot
spec:
  selector:
    name: springboot
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP 
